cms/urls.py
from django.urls import path, include

from . import views




app_name = 'cms'

urlpatterns = [
    path('', views.index1, name='top'),
    path('circleid-1-2/', views.index2, name='circleid-1-2'),
    path('circleid-1-3/', views.index3, name='circleid-1-3'),
    path('circleid-2-1/', views.index21, name='circleid-2-1'),
    path('circleid-2-2/', views.index22, name='circleid-2-2'),
    path('circleid-2-3/', views.index23, name='circleid-2-3'),
    path('circleid-3-1/<int:circle_id>/', views.index31, name='circleid-3-1'),
    path('circleid-3-2/<int:circle_id>/', views.index32, name='circleid-3-2'),
    path('circleid-3-3/<int:circle_id>/', views.index33, name='circleid-3-3'),
    path('userid/', views.mylist, name='userid'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('user/<int:pk>/update/', views.UserUpdate.as_view(), name='user_update'),
    path('user/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user/', views.UserList.as_view(), name='user_list'),
    path('user/<int:pk>/delete/', views.UserDelete.as_view(), name='user_delete'),
    path('add/', views.add, name='add'),
    path('dislike/', views.dislike, name='dislike'),
    path('delete/<int:circle_id>/', views.delete, name='delete'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('kiyaku/', views.KiyakuView.as_view(), name='kiyaku'),
    path('privacypolicy/', views.PrivacyView.as_view(), name='privacypolicy'),
]

config/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cms.urls')),
]

cms/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.base_user import (
    AbstractBaseUser, BaseUserManager,
)
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.db import models
from django.forms import ModelForm
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

#from FileExtensionValidator import views
# User-related
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class AbstractUser(AbstractBaseUser, PermissionsMixin):

    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    email = models.EmailField(_('email address'), unique=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    twitter = models.CharField(_('Twitter'), max_length=50, blank=True)
    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        abstract = True

    def __str__(self):
        return self.email

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        swappable = "AUTH_USER_MODEL"

class Circle(models.Model):
    circle_id = models.IntegerField()
    name = models.CharField(max_length=100)
    photo_1 = models.CharField(max_length=150)
    photo_2 = models.CharField(max_length=150)
    photo_3 = models.CharField(max_length=150)
    tag_1 = models.CharField(max_length=50)
    tag_2 = models.CharField(max_length=10)
    tag_3 = models.CharField(max_length=10)
    content = models.TextField(max_length=2000)
    mail = models.CharField(max_length=50, blank=True, null=True)
    twitter = models.CharField(max_length=50, blank=True, null=True)
    

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='like_user')
    circle = models.ForeignKey(Circle, on_delete=models.CASCADE, related_name='liked_circle')

class LikeForm(ModelForm):
    class Meta:
        model = Like
        fields = ['user', 'circle']
        exclude = ['user', 'circle']

#attach = models.FileField(
#        upload_to='cms/static/images/',
#        verbose_name='添付ファイル',
#        validators=[FileExtensionValidator(['pdf', ])],
#    )

cms/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms

UserModel = get_user_model()

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ('username', 'first_name', 'last_name', 'email','twitter')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       self.fields['username'].widget.attrs['class'] = 'input'
       self.fields['password'].widget.attrs['class'] = 'input'

class UserCreateForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'

cms/views.py
from django.contrib.auth import get_user_model, login
from django.contrib.auth.views import (
    LoginView, LogoutView,
)
from django.http import HttpResponseRedirect
from django.shortcuts import resolve_url, render
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import (
    CreateView, UpdateView,
)

from .mixins import OnlyYouMixin
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm,
)
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import (
    CreateView, UpdateView, DeleteView,
)

from .models import (Circle, Like, LikeForm)
import random

UserModel = get_user_model()
count = Circle.objects.all().count()
l = random.sample(range(1,count+1), k=count)
number = 0
x = 1

def index1(request):
    global x
    global l
    global number
    if request.user.is_authenticated:
        time = 1
        while True:
            i = l[number]
            if time > count:
                x = 0
                break
            elif not (Like.objects.filter(user=request.user, circle__circle_id=i).exists()):
                x = i
                break
            elif number < count - 1:
                number += 1
                time += 1
            else:
                number = 0
                time += 1
                l = random.sample(range(1, count + 1), k=count)
    data = Circle.objects.filter(circle_id=x)
    user = request.user
    params = {
        'data':data,
        'user':user
    }
    return render(request, 'cms/circleid-1-1.html', params)

def index2(request):
    data = Circle.objects.filter(circle_id=x)
    user = request.user
    params = {
        'data':data,
        'user':user
    }
    return render(request, 'cms/circleid-1-2.html', params)

def index3(request):
    data = Circle.objects.filter(circle_id=x)
    user = request.user
    params = {
        'data': data,
        'user': user
    }
    return render(request, 'cms/circleid-1-3.html', params)

def index21(request):
    data = Circle.objects.filter(circle_id=x)
    user = request.user
    params = {
        'data': data,
        'user': user
    }
    return render(request, 'cms/circleid-2-1.html', params)

def index22(request):
    data = Circle.objects.filter(circle_id=x)
    params = {
        'data':data
    }
    return render(request, 'cms/circleid-2-2.html', params)

def index23(request):
    data = Circle.objects.filter(circle_id=x)
    params = {
        'data':data
    }
    return render(request, 'cms/circleid-2-3.html', params)

def index31(request, circle_id):
    data = Circle.objects.filter(circle_id=circle_id)
    params = {
        'data':data
    }
    return render(request, 'cms/circleid-3-1.html', params)

def index32(request, circle_id):
    data = Circle.objects.filter(circle_id=circle_id)
    params = {
        'data':data
    }
    return render(request, 'cms/circleid-3-2.html', params)

def index33(request, circle_id):
    data = Circle.objects.filter(circle_id=circle_id)
    params = {
        'data':data
    }
    return render(request, 'cms/circleid-3-3.html', params)

def mylist(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('../signup/')
    else:
        data = Like.objects.filter(user=request.user)
        params = {
            'data':data
        }
        return render(request, 'cms/userid.html', params)

def add(request):
    global x
    global number
    global l
    if not request.user.is_authenticated:
        return HttpResponseRedirect('../signup/')
    else:
        t1 = Like()
        t1.user = request.user
        circle = Circle.objects.get(circle_id=x)
        t1.circle = circle
        t = LikeForm(request.POST, instance=t1)
        t.save()
        time = 1
        while True:
            i = l[number]
            if time > count:
                x = 0
                break
            elif not (Like.objects.filter(user=request.user, circle__circle_id=i).exists()):
                x = i
                break
            elif number < count-1:
                number += 1
                time += 1
            else:
                number = 0
                time += 1
                l = random.sample(range(1, count + 1), k=count)
        return HttpResponseRedirect('../')

def dislike(request):
    global x
    global number
    global l
    if not request.user.is_authenticated:
        time = 1
        while True:
            i = l[number]
            x = i
            if number < count - 1:
                number += 1
            else:
                l = random.sample(range(1, count + 1), k=count)
                number = 0
            break
    else:
        time = 1
        while True:
            i = l[number]
            if time > count:
                x = 0
                break
            elif not (Like.objects.filter(user=request.user, circle__circle_id=i).exists()):
                x = i
                if number < count - 1:
                    number += 1
                else:
                    l = random.sample(range(1, count + 1), k=count)
                    number = 0
                break
            elif number < count - 1:
                number += 1
                time += 1
            else:
                number = 0
                time += 1
                l = random.sample(range(1, count + 1), k=count)
    return HttpResponseRedirect('../')

class Login(LoginView):
    form_class = LoginForm
    template_name = 'cms/login.html'

class Logout(LogoutView):
    pass

class UserCreate(CreateView):
    form_class = UserCreateForm
    template_name = 'cms/signup.html'
    success_url = reverse_lazy('cms:top')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())

class UserUpdate(OnlyYouMixin, UpdateView):
    model = UserModel
    form_class = UserUpdateForm
    template_name = 'cms/user_update.html'

    def get_success_url(self):
        return resolve_url('cms:user_detail', pk=self.kwargs['pk'])

class UserDetail(DetailView):
    model = UserModel
    template_name = 'cms/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context

class UserList(ListView):
    model = UserModel
    template_name = 'cms/user_list.html'

class UserDelete(OnlyYouMixin, DeleteView):
    model = UserModel
    template_name = 'cms/user_delete.html'
    success_url = reverse_lazy('cms:top')


def delete(request, circle_id):
    Like.objects.filter(user=request.user, circle__circle_id=circle_id).delete()
    return HttpResponseRedirect('../../userid')

class AboutView(TemplateView):
    template_name = 'cms/about.html'

class KiyakuView(TemplateView):
    template_name = 'cms/kiyaku.html'

class PrivacyView(TemplateView):
    template_name = 'cms/privacy.html'

cms/templates/cms/about.html
<!doctype html>
<html lang="ja">

{% extends 'cms/base.html' %}

{% block title %}About | {% endblock %}

{% block content %}


<head>
<meta charset="UTF-8">
<title>About</title>
<link href="../../static/css/about.css" rel="stylesheet" type="text/css">
</head>

<body>
<div id="main">
  <h1>おうちでテント列</h1>
    <p>
      <br>
    　UTiCは新型コロナウイルスの影響で新歓活動の機会を失った東京大学のサークル・部活を支援するサービスです。<br>
      <br>
    </p>

  <h1>「UTiC」：the University of Tokyo introduction of Circles</h1>
    <p>
      <br>
    「UTiC」はthe University of Tokyo introduction of Circles の略称として名付けられました。<br>
      <br>
    </p>

  <h1>失われた「偶然の出会い」</h1>
    <p>
      <br>
      新入生からはテント列やビラ配りで検討するはずだったサークルとの出会いがなくなり，選択の幅が狭まってしまっている，という課題がありました。<br>
      <br>
    </p>

  <h1>「貴重な機会が失われてしまった...」</h1>
    <p>
      <br>
      サークル・部活からは新入生に知ってもらう貴重な機会が失われ，オンラインでもなかなか自分のサークル・部活を目にしてもらえないという課題がありました。<br>
      <br>
    </p>

  <h1>TinderライクなUI</h1>
    <p>
      <br>
      これらの課題を解決すべく，ランダムにサークル・部活を表示することで思わぬサークル・部活との出会いがある，そんなWEBアプリ制作を目指しました。<br>
      <br>
    </p>

  <h1>3人・4週間で作成</h1>
    <p>
      <br>
      作成チームは東京大学に所属する有志三年生3人です(理学部・工学部・後期教養学部所属)。企画・作成・ローンチは約4週間で終えました。<br>
      <br>
    </p>

  <h1>UTokyo Project Sprint公認団体</h1>
    <p>
      <br>
      UTiCは<a href="https://sites.google.com/g.ecc.u-tokyo.ac.jp/utokyo-project-sprint/">UTokyo Project Sprint</a>公認団体です。<br>
      <br>
  </p>

  <h1>6月1日(月)正式版公開</h1>
    <p>
      <br>
      05月01日(金)　運営チーム結成<br>
      05月28日(木)　β版公開<br>
      06月01日(月)　正式版公開<br>
      <br>
    </p>

  <h1>Thank you for You</h1>
    <p>
      <br>
      ローンチに至るまでたくさんの方々にお世話になりました。この場を借りて御礼申し上げます。誠にありがとうございました。
      <br>
    </p>

  <h1>New Gear Coming Soon</h1>
    <p>
      <br>
      「選択授業の仕分け」や「学部学科の仕分け」への応用も検討しています。
      <br>
    </p>

</div>

</body>

{% endblock %}

</html>

cms/templates/cms/index.html
<!--<html>-->
<!--<head></head>-->
<!--<body>-->
<!--&lt;!&ndash;  todoリストにものが入ってるかどうか確認して入ってたら表を表示&ndash;&gt;-->
<!--&lt;!&ndash;&ndash;&gt;-->
<!--    <table>-->
<!--&lt;!&ndash;      ここに登録したものの表が作られ，削除ボタンも作られています&ndash;&gt;-->
<!--      <tr>-->
<!--        <td>id</td>-->
<!--      </tr>-->
<!--      <tr>-->
<!--      </tr>-->
<!--      -->
<!--    </table>-->
<!--&lt;!&ndash; &ndash;&gt;-->
<!--&lt;!&ndash;  何もなかったらNo todos と表示するように設定しています&ndash;&gt;-->
<!--&lt;!&ndash;      <p>No todos are available.</p>&ndash;&gt;-->
<!--&lt;!&ndash;  &ndash;&gt;-->
<!--  </body>-->
<!--</html>-->


<!--初期値は-->
<html>


<head></head>
<body>
  <a href="/new">登録</a>
    <table>
      <tr>
        <td>id</td>
        <td>title</td>
        <td></td>
      </tr>
      <tr>
        <td><a href="/cms/{{ todo.todo_id }}/">{{ todo.todo_id }}</a></td>
        <td>{{ todo.title }}</td>
        <td><a href="/delete/{{ todo.todo_id }}/">削除</a></td>
      </tr>
    </table>

  </body>
</html>

cms/templates/cms/login.html
{% extends 'cms/base.html' %}

{% block title %}Login | {% endblock %}

{% block content %}

<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">ログイン</h1>
        <h2 class="subtitle is-6">Login</h2>
        <hr>
        <p class="help">アカウントをお持ちでない方へ：サインアップは<a href="{% url 'cms:signup' %}">こちら</a></p>
        <br>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">パスワード</label>
                <div class="control has-icons-left">
                    {{ form.password }}
                    <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                </div>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="ログイン" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
    </div>

</section>
{% endblock %}

cms/templates/cms/new.html
<!--<html>-->
<!--<head></head>-->
<!--<body>-->
<!--&lt;!&ndash;ここを修正。action=でデータの渡し先を指定しています&ndash;&gt;-->
<!--  <form action="../add/" method="post">-->
<!--    }-->
<!--&lt;!&ndash;    隠しフォームで入力します。入力内容はtodo.todo_id(models.pyのTodo classに定義されている)で，models.py中のtodo_idというハコに格納されます&ndash;&gt;-->
<!--    <input type="hidden" name="todo_id" value=""/>-->
<!--&lt;!&ndash;    いいねボタンで提出できます&ndash;&gt;-->
<!--    <input type="submit" value="いいね"/>-->
<!--  </form>-->
<!--</body>-->
<!--</html>-->

<html>


<head></head>
<body>
  <form action="../add/{% if todo %}{{ todo.todo_id }}/{% endif %}" method="post">
    {% csrf_token %}
    title: <input type="text" name="title" value="{{ todo.title }}"/>
    main: <input type="text" name="main_text" value="{{ todo.main_text }}"/>
    <input type="hidden" name="todo_id" value="{{ todo.todo_id }}"/>
    <input type="submit" value="登録"/>
  </form>

</body>

cms/templates/cms/signup.html
{% extends 'cms/base.html' %}

{% block title %}Signup | {% endblock %}

{% block content %}

<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">サインアップ</h1>
        <h2 class="subtitle is-6">Sign up</h2>
        <hr>
        <p class="help">アカウントをお持ちの方へ：ログインは<a href="{% url 'cms:login' %}">こちら</a></p>
        <br>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">メールアドレス</label>
                <div class="control has-icons-left">
                    {{ form.email }}
                    <span class="icon is-small is-left"><i class="fas fa-envelope"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">パスワード</label>
                <div class="control has-icons-left">
                    {{ form.password1 }}
                    <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">パスワード（確認）</label>
                <div class="control has-icons-left">
                    {{ form.password2 }}
                    <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                </div>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="登録" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
    </div>
</section>

{% endblock %}

cms/templates/cms/top.html
{% extends 'cms/base.html' %}

{% block title %}Home | {% endblock %}

{% block hero %}

<section class="hero is-medium is-info is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Title</h1>
            <h2 class="subtitle">Subtitle</h2>
            <a href="#">
                <button class="button is-info is-inverted is-outlined">
                    <strong>More Info</strong>
                </button>
            </a>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="section is-medium">
    <div class="container">
        <div class="has-text-centered">
            <h1 class="title">Section</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>
    </div>
</section>


{% endblock %}

cms/templates/cms/user_detail.html
{% extends 'cms/base.html' %}

{% block title %}{{ user.last_name }} {{ user.first_name }} | {% endblock %}

{% block hero %}

<section class="hero is-link is-bold">
    <div class="hero-body">
        <div class="container">
            <div class="media">
                <div class="media-left">
                    <figure class="image is-64x64 is-left">
                        <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
                    </figure>
                </div>
                <div class="media-content">
                    <h1 class="title">
                        {{ user.last_name }} {{ user.first_name }}
                    </h1>
                    <h2 class="subtitle">
                        {{ user.username }}
                    </h2>
                    {% if user.pk == request.user.pk %}
                    <a href="{% url 'cms:user_update' user.pk %}">
                        <button class="button is-small is-info is-inverted is-outlined">
                            <span class="icon is-small is-left"><i class="fas fa-user-edit"></i></span>
                            <strong>プロフィールを追加する</strong>
                        </button>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="level">
            <div class="level-left">
                {% if user.twitter %}
                <div class="level-item">
                    <div class="tags has-addons">
                        <span class="tag"><span class="icon is-small is-left"><i class="fab fa-twitter"></i></span></span>
                        <span class="tag is-dark"><a class="has-text-white" href="https://twitter.com/{{ user.twitter }}" target="_blank">@{{ user.twitter }}</a></span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.</p>
    </div>
</section>

{% endblock %}

cms/templates/cms/user_list.html
{% extends 'cms/base.html' %}

{% block title %}ユーザー一覧 | {% endblock %}

{% block hero %}

<section class="hero is-small is-link is-bold">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title">ユーザー一覧</h1>
            <h2 class="subtitle">User List</h2>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="tile is-ancestor">
            <div class="tile is-12 is-vertical is-parent">
                {% for object in object_list %}
                <div class="tile is-child box">
                    <a class="title is-4" href="{% url 'cms:user_detail' object.id %}">{{ object.username }}</a>
                    <p>Lorem ipsum dolor sit</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

cms/templates/cms/user_update.html
{% extends 'cms/base.html' %}

{% block title %}{{ user.username }} | {% endblock %}

{% block content %}

<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">ユーザー情報の更新</h1>
        <h2 class="subtitle is-6">Update your information</h2>
        <hr>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">姓</label>
                <div class="control has-icons-left">
                    {{ form.last_name }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">名</label>
                <div class="control has-icons-left">
                    {{ form.first_name }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">メールアドレス</label>
                <div class="control has-icons-left">
                    {{ form.email }}
                    <span class="icon is-small is-left"><i class="fas fa-envelope"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">Twitter</label>
                <div class="control has-icons-left">
                    {{ form.twitter }}
                    <span class="icon is-small is-left"><i class="fab fa-twitter"></i></span>
                </div>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="保存" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
        <hr>
        <a href="{% url 'cms:user_delete' user.pk %}">
            <button class="button is-danger is-outlined">削除</button>
        </a>
    </div>
</section>
{% endblock %}